---
- name: Add unstable package sources
  apt_repository:
    repo: deb http://ftp.de.debian.org/debian buster main
    state: present
  tags:
    - pretalx

- name: Install Python 3
  apt:
    name:
      - python3
      - python3-dev
      - python3-pip
      - python3-wheel
    state: latest
    default_release: buster
  tags:
    - pretalx

- name: Install python-setuptools if Ansible is running with Python 2
  # The Ansible pip module needs setuptools available in the Python version
  # under which Ansible is running.
  # See https://github.com/ansible/ansible/issues/47361#issuecomment-433892723
  # for a more detailed explaination.
  apt:
    name: python-setuptools
    state: present
  when: ansible_python.version.major|int == 2
  tags:
    - pretalx

- name: Install other dependencies
  apt:
    name:
      - gcc
      - gettext
      - git
      - redis-server
      - sqlite3
    state: present
  tags:
    - pretalx
